### ISSUE TITLE
Electrophysiological feature extraction

### ISSUE THREAD

**Issue by hongruhu** [AllenInstitute/coupledAE-patchseq#1]
Hi, I was wondering if I download the dandi:000020 dataset (Gouwens et al., 2020 Cell) and I wanted to extract the fv, how could I determine the parameters in the argument (such as `ap_window_length`) since I could not find related information from the paper to determine the best duration (assuming I could apply the single value for all cells/nwb files). 

```
run_feature_vector_extraction(output_dir = "./path/", 
                              ap_window_length = 0.003,                           # 0.003 is just the default number by ipfx
                              data_source = "filesystem",
                              output_code = "feature_vector",
                              project = None,
                              output_file_type = "h5",
                              include_failed_cells = False,
                              sweep_qc_option = "none",                           # not sure if there's a way to operating sweep QC for "filesystem" downloaded nwb files
                              run_parallel = False,
                              ids = ids_list,
                              file_list=nwb_file_list)
```

It would be great if some of the preprocessing scripts are available.
Thank you very much!

**Comment by rhngla** [comment]
This is referencing the [run_feature_vector_extraction](https://github.com/AllenInstitute/ipfx/blob/95d7f00ad379897f3b88a7d6bcbb20f0a8107f8d/ipfx/bin/run_feature_vector_extraction.py) function in the ipfx repository. I believe you can use default parameters - @agatabudzillo is this accurate for ipfx features used in our manuscript?

PS: You can post more general queries for publicly released Allen Institute datasets on https://community.brain-map.org.

**Comment by hongruhu** [comment]
Yes, I used the function from the ipfx, but when creating the h5 file, it seemed that it could fail as for example, some samples have no spiking for specific “short square sweeps”. Also noticed that in your paper and also Gouwens' paper, not all the 4435 cells from DNADI:000020 were included, does that mean those cells excluded from the publication are dropped based on specific criteria? I also tried the drcme package to compute the sPCs, but it seems that specifying the parameter json file requires some prior knowledge (e.g. choosing first 300 points of the data to leave the ramp AP waveform out)... I was wondering if there is a way to match the selection as you did?

Thank you very much.

**Comment by agatabudzillo** [comment]
@rhngla @Hongru-Hu, yes, we used the default parameters for run_feature_vector_extraction.

The 4435 cells from DNADI:000020 include the inhibitory cells in (Gouwens et al., 2020 Cell) as well as ~170 excitatory cells. 

Yes, drcme expects a configuration file - you can find the one that we used in the Gouwens 2020 publication here: https://github.com/AllenInstitute/drcme/blob/master/config/spca_inh_patchseq_cell_2020_config.json
Thanks for letting us know that was missing!

Regarding the other ipfx processing issues that you are running into - if you could share some more specific errors and the specimen IDs that triggered them as an issue on either https://github.com/AllenInstitute/ipfx or https://community.brain-map.org we can look into it.
