### ISSUE TITLE
scRNA-seq data processing

### ISSUE THREAD

**Issue by big-rain** [AllenInstitute/coupledAE-patchseq#7]
Hi, While reading the data processing code you gave me, I noticed that you used some preprocessed files, 
such as data.feather,
             anno.feather,
            good_fenes_beta_score.csv,
            specimen_ids.txt;
           color_ref.csv,
However, from the scRNA-seq download address you gave, the above files were not found, only gene counting moment, bam, fastp files exist.

I would like to know how to obtain this data by analyzing raw scRNA-seq data from the above files. Can you provide more detailed code to help me analyze it?

**Comment by rhngla** [comment]
**1. `data.feather` + `anno.feather`**

As you already know, the `data.feather` (expression values) and `anno.feather` (per-cell annotations, including cell type labels used in the paper) files were used to produce the `.mat` file included in the repository. These files roughly correspond to the count data and metadata files [available here](https://data.nemoarchive.org/other/AIBS/AIBS_patchseq/transcriptome/scell/SMARTseq/processed/analysis/20200611/). I had included notebooks only for reference, not intended to be run by users 😁

**2. beta scores + gene selection**

The `.mat` file contains log-cpm normalized expression values for a pre-selected gene set. The set of genes was obtained using the beta score (a description of this score is can be found in the associated paper). I have now included beta scores assigned to each gene in [`genes_beta_score.csv`](https://github.com/AllenInstitute/coupledAE-patchseq/blob/cplAE-TE/data/proc/genes_beta_score.csv) in case that is of interest. I expect any reasonable strategy to reduce the set of genes (e.g. highly variable genes, differentially expressed genes etc.) would roughly provide similar results, and the methodology with coupled autoencoders is agnostic to that. 

**3. other links**

Check [this closed issue](https://github.com/AllenInstitute/coupledAE-patchseq/issues/4) and [Gouwens et al. 2020](https://www.sciencedirect.com/science/article/pii/S009286742031254X) for less processed versions of the data. This [Allen Institute page](https://knowledge.brain-map.org/data/1HEYEW7GMUKWIQW37BO/specimens/) may also be of interest to you.

**Comment by big-rain** [comment]
Can you provide working scRNA-seq data preprocessing code, from count matrices to .mat files？

**Comment by rhngla** [comment]
Hi - please use any standard pipeline (e.g. through scanpy) to process the raw data in the data and metadata `.csv` files linked above; you can add the exon and intron data to get a single counts matrix and then perform log-cpm normalization.
